fail_fast: true
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: check-symlinks
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: debug-statements
        exclude: |
          (?x)(
              ^python3/05_Debugging/ |
              ^python3/14_Code_Quality/python_2to3_ex.py
          )
      - id: destroyed-symlinks
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-ast
        exclude: python3/14_Code_Quality/python_2to3_ex.py
      # - id: check-shebang-scripts-are-executable

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        exclude: python3/14_Code_Quality/python_2to3_ex.py

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.9.2
  #   hooks:
  #     - id: flake8
